### ISSUE TITLE
[feat]: positional options for wrong-position letters

### ISSUE THREAD

**Issue by jaydgruber** [trabus/wordle-finder#10]
I think it would be neat to be able to add a row-per yellow letter to be able to indicate which positional slots you have ruled out for that letter. Instead of just "this letter is in there somewhere"

**Comment by jaydgruber** [comment]
For example, if I have

```
correct position: [q, u, _, _, _]
Incorrect position: {
  'e': [2], // index. I can think of other ways to structure
}
```

I would expect `queen` to not be in results
I would expect `quiet` to be in results

**Comment by trabus** [comment]
Huh, that's a good idea!
![Screen Shot 2022-02-10 at 8 46 46 AM](https://user-images.githubusercontent.com/324797/153455468-2e52b057-4b34-498a-be76-9bb40229fe63.png)

**Comment by trabus** [comment]
![Screen Shot 2022-02-10 at 8 49 58 AM](https://user-images.githubusercontent.com/324797/153455981-b9a65823-5a35-411b-ba75-ee2b04d0f69b.png)
Coming soon in a release tonight after some cleanup on the refactor. I had to do a lot of adjustment to untangle some stuff I had been a bit sloppy with at first during my creative coding burst.

Now I've got models/delegates for each of the entities (letter, tray, words, finder) that will open the door for some fun control schemes.

**Comment by trabus** [comment]
Oh, I also added double letter support finally!

**Comment by trabus** [comment]
Almost done with this feature, just going to add duplicate support. There are cases where you'll try the same letter in a different slot and it will also be included but in the wrong spot. I also am going to try and make sure the act of placing the letter in a green slot doesn't remove the existing yellow ones like it currently does (though it might not be possible with the way I've written it at this point).

**Comment by trabus** [comment]
added duplicate support.
